### ISSUE TITLE
CLP-S: Undefined behavior on file with no read permission

### ISSUE THREAD

**Issue by haiqi96** [y-scope/clp#325] opened 2024-03-13 21:11 UTC
### Bug

When using CLP-S to compress a file, if the file exists but doesn't have read permission, CLP-S will silently finish and generate an archive instead of reporting a failure.

### CLP version

74ac2949a4a34a4687d945229270f2b9d2900e51

### Environment

Ubuntu22.04

### Reproduction steps

```
chmod 000 <log_file>
clp-s c output <log_file>
```

**Comment by gibber9809** [comment] 2024-03-13 21:30
This should be solved by #310 once it is merged. I confirmed that trying to compress a file without read permission now results in a bunch of error logs & exit status 1.

**Comment by gibber9809** [comment] 2024-03-16 23:44
Closing since #310 has been merged.

**Closed** 2024-03-16 23:43 UTC
Labels: bug
